Fix an error for `FactoryBot/ConsistentParenthesesStyle` cop
```
  1) RuboCop::Cop::FactoryBot::ConsistentParenthesesStyle when EnforcedStyle is :omit_parentheses registers an offense with `kwsplat` node argument
     Failure/Error: factory_call(node) { register_offense(node) }

     NoMethodError:
       undefined method 'value_omission?' for an instance of RuboCop::AST::KeywordSplatNode
     # ./lib/rubocop/cop/factory_bot/consistent_parentheses_style.rb:96:in 'block in RuboCop::Cop::FactoryBot::ConsistentParenthesesStyle#omit_hash_value?'
     # ./lib/rubocop/cop/factory_bot/consistent_parentheses_style.rb:94:in 'RuboCop::Cop::FactoryBot::ConsistentParenthesesStyle#omit_hash_value?'
     # ./lib/rubocop/cop/factory_bot/consistent_parentheses_style.rb:111:in 'RuboCop::Cop::FactoryBot::ConsistentParenthesesStyle#register_offense_with_parentheses'
     # ./lib/rubocop/cop/factory_bot/consistent_parentheses_style.rb:104:in 'RuboCop::Cop::FactoryBot::ConsistentParenthesesStyle#register_offense'
     # ./lib/rubocop/cop/factory_bot/consistent_parentheses_style.rb:96:in 'block in RuboCop::Cop::FactoryBot::ConsistentParenthesesStyle#on_send'
     # ./lib/rubocop/cop/factory_bot/consistent_parentheses_style.rb:83:in 'RuboCop::Cop::FactoryBot::ConsistentParenthesesStyle#factory_call'
     # ./lib/rubocop/cop/factory_bot/consistent_parentheses_style.rb:96:in 'RuboCop::Cop::FactoryBot::ConsistentParenthesesStyle#on_send'
     # ./spec/rubocop/cop/factory_bot/consistent_parentheses_style_spec.rb:468:in 'block (3 levels) in <top (required)>'
```