Handle hash keys other than symbols
When processing the following code:

   FactoryBot.define do
     factory :post do
       options Tag::MAGIC => :magic
     end
   end

FactoryBot/AttributeDefinedStatically raises NoMethodError
because the node of `Tag::MAGIC` does not respond to `value`.

   Failure/Error: hash_node.keys.any? { |key| key.value == :factory }

   NoMethodError:
     undefined method `value' for "s(:const,\n  s(:const, nil, :Tag), :MAGIC)":RuboCop::AST::Node

It seems that `association` method decides whether the method call is for
association or not as factory_bot/definition_proxy.rb [1] does and we can safely
ignore keys other than symbols. So this PR just adds a check for node types.

[1]: https://github.com/thoughtbot/factory_bot/blob/4888e1d4ac839229a77343f314b2a2ed3f1cd5c2/lib/factory_bot/definition_proxy.rb#L100-L101