Fix an error for `FactoryBot/AssociationStyle` cop
```shell
  1) RuboCop::Cop::FactoryBot::AssociationStyle when EnforcedStyle is :explicit when implicit association is called in trait block does not register an offense for `trait` without `factory` block
     Failure/Error:
       def autocorrect(corrector, node)
         if style == :explicit
           autocorrect_to_explicit_style(corrector, node)
         else
           autocorrect_to_implicit_style(corrector, node)
         end

     NoMethodError:
       undefined method 'each_node' for nil
     # ./lib/rubocop/cop/factory_bot/association_style.rb:149:in 'RuboCop::Cop::FactoryBot::AssociationStyle#trait_name'
     # ./lib/rubocop/cop/factory_bot/association_style.rb:254:in 'Enumerator#each'
     # ./lib/rubocop/cop/factory_bot/association_style.rb:254:in 'Enumerable#include?'
     # ./lib/rubocop/cop/factory_bot/association_style.rb:254:in 'RuboCop::Cop::FactoryBot::AssociationStyle#trait_within_trait?'
     # ./lib/rubocop/cop/factory_bot/association_style.rb:179:in 'RuboCop::Cop::FactoryBot::AssociationStyle#bad?'
     # ./lib/rubocop/cop/factory_bot/association_style.rb:201:in 'block in RuboCop::Cop::FactoryBot::AssociationStyle#bad_associations_in'
     # ./lib/rubocop/cop/factory_bot/association_style.rb:200:in 'Array#select'
     # ./lib/rubocop/cop/factory_bot/association_style.rb:200:in 'RuboCop::Cop::FactoryBot::AssociationStyle#bad_associations_in'
     # ./lib/rubocop/cop/factory_bot/association_style.rb:84:in 'RuboCop::Cop::FactoryBot::AssociationStyle#on_send'
     # ./spec/rubocop/cop/factory_bot/association_style_spec.rb:319:in 'block (4 levels) in <top (required)>'
```